### ISSUE TITLE
Rocket conflicts with env_logger

### ISSUE THREAD

**Issue by GoldenBadger** [redbrick/good_stv#17]
# Problem

Rocket comes with its own error backend, so our use of `env_logger` is conflicting with it, which is causing output like:
```
ERROR 2018-03-15T16:02:10Z: rocket::rocket: 🚀  Rocket has launched from http://localhost:8000
```

# Proposed solution

The solution is to remove `env_logger`, but that introduces another problem: our own logging won't be formatted how we like it.

# Proposed solution 2

If we switch from the official error frontend, [`log`](https://github.com/rust-lang-nursery/log), to the popular alternative [`slog`](https://github.com/slog-rs/slog), then we have control over what parts of the program are logged in what way. Our code can be logged in a completely separate way to Rocket.

While doing this I will also look into changing how logging works in the library.

**Comment by GoldenBadger** [comment]
@butlerx @theycallmemac Thoughts?

**Comment by butlerx** [comment]
though 2 sounds like more work it seems like the better option so it gets my vote

**Comment by theycallmemac** [comment]
better off doing the latter, so yeah also has my vote also 👍

**Comment by butlerx** [comment]
@GoldenBadger i believe #23 solves this

**Comment by GoldenBadger** [comment]
Yep it does, thanks for reminding me.
